---
# local
spring:
  config:
    activate:
      on-profile: local
who:
  am:
    i: this-local
---
# test
spring:
  config:
    activate:
      on-profile: test
who:
  am:
    i: this-test
---
# add
spring:
  config:
    activate:
      on-profile: add
who:
  am:
    i: this-add
